import { useNavigate, useParams } from 'react-router-dom';
import { NAVY, MUTED, BLUE, FONT_HEAD } from '../styles/theme';

const LEGAL_DOCS = {
  terms: {
    num: '01',
    label: 'Terms of Service',
    title: 'Terms of Service',
    version: 'v1',
    applies: 'Applies to every visitor, customer, and business using any Saw Yun LLC product or service.',
    intro: 'Welcome to Saw Yun LLC. These Terms of Service ("Terms") govern your access to and use of all products, software, websites, applications, online services, downloadable software, cloud services, APIs, customer portals, license activation services, and any other services provided by Saw Yun LLC ("Saw Yun LLC," "Saw Yun," "we," "us," or "our"). By accessing, downloading, installing, registering for, purchasing, or using any of our Services, you agree to be bound by these Terms. These Terms apply to individuals, businesses, organizations, and any other entity using our Services. Some Services may be subject to additional product-specific terms — such as our End User License Agreement or Reseller & Referral Partner Agreement — which supplement these Terms and govern in case of conflict on the matters they specifically address.',
    sections: [
      ['About Saw Yun LLC', 'Saw Yun LLC is an independent software company registered in the State of Montana, United States. We develop and operate business software, cloud services, desktop applications, web applications, APIs, mobile applications, licensing systems, and related technologies for customers worldwide, including business management software, point-of-sale systems, inventory management systems, repair management systems, license management systems, cloud-based software services, desktop software, mobile applications, and future software products released under the Saw Yun LLC brand.'],
      ['Definitions', 'In these Terms: "Account" means a registered account used to access one or more Services. "Business Customer" means a company, organization, partnership, sole proprietor, or other legal entity using our Services. "Customer" means any individual or organization using our Services. "Content" means any text, files, images, data, databases, software, documents, configurations, or other information stored, submitted, uploaded, transmitted, or generated through our Services. "License" means permission granted by Saw Yun LLC to use certain Software under specific conditions. "Software" means any desktop application, web application, cloud service, mobile application, downloadable program, installer, update, API, or related software we provide. "Services" means all products, software, websites, applications, APIs, cloud services, customer portals, downloads, support services, licensing systems, AI-powered features, integrations, and any future products or services we operate. "Subscription" means a recurring paid plan that grants access to certain Services. "Trial" means a limited-time evaluation period offered at no cost. "User" means any person or organization accessing or using our Services.'],
      ['Eligibility', 'To use our Services, you must be at least eighteen (18) years of age, have the legal authority to enter into a binding agreement, comply with all applicable laws and regulations, and provide accurate information when requested. If you are using our Services on behalf of a business or organization, you represent that you have authority to bind that organization to these Terms.'],
      ['User Accounts', 'Some Services require an Account. You agree to provide accurate and current information, keep your account credentials confidential, maintain the security of your account, and notify us promptly of any unauthorized access or suspected security incident. You are responsible for all activity conducted through your Account unless caused by our negligence or a security issue within our systems. We reserve the right to suspend or terminate Accounts that violate these Terms or create security risks.'],
      ['Our Services', 'Saw Yun LLC provides software products and related services designed primarily for businesses, which may include software subscriptions, desktop software licenses, cloud-hosted applications, license activation services, software updates, technical support, customer portals, APIs, and future products. Certain Services may require registration, identity verification, license activation, payment, administrative approval, and/or additional agreements, and availability of specific features depends on your purchased plan, license, subscription, or product.'],
      ['Acceptable Use', 'You agree to use our Services responsibly and lawfully. You must not violate any applicable law or regulation; attempt to gain unauthorized access to our systems or another customer’s account; circumvent licensing, subscription, activation, or security mechanisms; reverse engineer, decompile, or disassemble our Software except where permitted by law; distribute malware or harmful code; use our Services for fraudulent, deceptive, abusive, or illegal activity; interfere with or attempt to overload or damage our infrastructure; resell or redistribute our Software without written authorization; or share license credentials in violation of your purchased license. We may investigate suspected violations and suspend or terminate access accordingly.'],
      ['Business Customer Responsibilities', 'Business Customers are responsible for the accuracy of information entered into the Services; compliance with applicable tax, accounting, labor, consumer protection, and other legal obligations; managing employees’ access permissions; maintaining secure passwords; keeping independent backups of critical business records where appropriate; and ensuring uploaded content is lawful and properly licensed. Saw Yun LLC does not verify the accuracy of customer-entered business data and is not responsible for business decisions made using our Services.'],
      ['Intellectual Property', 'All Software, source code, user interfaces, graphics, logos, trademarks, documentation, designs, databases, and other materials we provide are owned by Saw Yun LLC or its licensors and protected by applicable intellectual property laws; these Terms do not transfer any ownership to you. Except as expressly permitted, you may not copy, modify, create derivative works of, sell, or sublicense our Software, remove copyright notices or license protection mechanisms, or use our trademarks without written permission. You retain ownership of the business data, documents, and content you upload or create using our Services, and you grant Saw Yun LLC only the limited rights necessary to host, process, transmit, back up, and display that data to provide the Services to you.'],
      ['Subscriptions', 'Certain Services are offered through recurring subscription plans. Unless otherwise stated for a specific product, subscription fees are charged in advance, access continues for the purchased billing period, and plans may differ in available features, storage, devices, users, branches, products, customers, or other usage limits, which are determined by the purchased subscription and may change for future plans or products. We may introduce, modify, or discontinue subscription plans, with reasonable notice to existing customers where required.'],
      ['Software Licenses', 'Certain Software is provided under a license rather than sold. Purchasing a license grants you a limited, non-exclusive, non-transferable, revocable right to use the Software according to the applicable license terms and our End User License Agreement. Unless expressly permitted, licenses may not be shared, resold, or transferred to another person or organization without our written approval, and license usage and limits are subject to the activation policies applicable to your purchased product.'],
      ['License Activation', 'Some Software requires online activation before use, which may include verification of your license key, customer account, device information, product version, and activation eligibility. Device activation limits depend on your purchased license or subscription; requests to transfer or replace activated devices may be approved according to our activation policies; and attempts to bypass or interfere with the activation system may result in suspension or permanent revocation of the affected license.'],
      ['Free Trials', 'We may offer free trial programs for selected Services, currently including a Standard Free Trial and a Referral Trial. Unless otherwise stated, trials are intended solely for evaluation, may include usage limitations, and expire automatically; we may modify or discontinue trial programs at any time, and expiration of a trial does not automatically create a paid subscription.'],
      ['Pricing and Payments', 'Prices are displayed in the applicable currency for the relevant product or market. We may accept various payment methods depending on product availability, customer location, or administrative approval, including bank transfers, mobile payment services, digital wallets, online payment providers, and other approved methods. You are responsible for ensuring your payment information and references are accurate, and where manual payment verification is required, access to paid Services may begin only after payment is confirmed.'],
      ['Taxes', 'Unless expressly stated otherwise, prices do not include applicable taxes, duties, or government fees. You are responsible for any taxes required under the laws applicable to your purchase or use of the Services; we will collect taxes only where legally required.'],
      ['Renewals and Cancellations', 'Subscription Services continue for the purchased billing period. You may cancel a subscription at any time; cancellation prevents future renewals but does not automatically entitle you to a refund for the current billing period. Unless otherwise required by law, access continues until the end of your paid subscription period and previously paid fees remain non-refundable except as described in our Refund Policy.'],
      ['Refunds', 'Refund eligibility is governed by our Refund Policy, which forms part of these Terms. In general, successful software license activations and subscription fees are non-refundable after payment, though duplicate payments, billing errors, failed activations that cannot reasonably be resolved, or refunds required by applicable law may qualify.'],
      ['Reseller Program', 'Saw Yun LLC may operate reseller, affiliate, referral, or partner programs for eligible Services, subject to eligibility requirements and our Reseller & Referral Partner Agreement. Resellers agree to represent our products honestly, avoid misleading marketing, comply with applicable laws, and follow our branding guidelines where provided. We reserve the right to review commission eligibility, delay payouts under review, reverse or adjust commissions tied to fraudulent, refunded, canceled, or invalid transactions, and suspend or terminate reseller participation for violations. Participation in a reseller program does not create an employment, agency, franchise, or partnership relationship.'],
      ['Technical Support', 'We provide support through the communication channels we designate, currently email, with Telegram, Viber, TikTok, and YouTube planned as additional channels. Typical support hours are Monday–Friday, 9:00 AM–5:00 PM (Indochina Time, UTC+7), though hours are subject to change and we may occasionally be unavailable on business days without prior notice. Support availability, response times, and supported languages may vary by product or subscription plan, and we do not guarantee resolution times unless expressly agreed in writing.'],
      ['Software Updates', 'We may provide updates, improvements, patches, bug fixes, security enhancements, and new features, which may be automatic, manual, optional, or required for continued compatibility or security. Failure to install required updates may limit functionality or prevent access to certain Services.'],
      ['Availability', 'We strive to provide reliable Services but do not guarantee uninterrupted availability. Services may become temporarily unavailable due to maintenance, security updates, network or infrastructure failures, third-party service interruptions, force majeure events, or other circumstances beyond our reasonable control, and we may perform scheduled maintenance with or without prior notice where necessary.'],
      ['Suspension', 'We may suspend access to some or all Services if we reasonably believe these Terms have been violated, fraudulent activity has occurred, payment obligations remain outstanding, or a security incident threatens our systems, other customers, or creates legal or operational risk. Where practical, we will attempt to notify affected customers before or shortly after suspension.'],
      ['Termination', 'You may stop using our Services at any time. We may terminate or discontinue access if these Terms are materially violated, fraudulent or unlawful activity occurs, required payments remain unpaid, continued service is no longer commercially or technically feasible, or we are required to do so by law. Termination does not remove obligations that arose beforehand, and sections concerning intellectual property, payment obligations, disclaimers, limitation of liability, governing law, dispute resolution, and other provisions intended to survive will remain in effect after termination.'],
      ['Privacy', 'Your use of our Services is also governed by our Privacy Policy, which explains what information we collect, why we collect it, how we use and protect it, how long we retain it, and your available rights. By using our Services, you acknowledge that your information will be processed in accordance with our Privacy Policy.'],
      ['Customer Data', 'You retain ownership of all lawful data, documents, databases, inventory records, customer information, employee information, financial records, and other content you submit or create through our Services ("Customer Data"); we do not claim ownership of it. You grant Saw Yun LLC a limited, worldwide, non-exclusive, royalty-free license to host, store, process, transmit, back up, and display Customer Data solely as necessary to operate and provide the Services, and you are responsible for ensuring you have the legal right to collect and process any personal information entered into our Services.'],
      ['Data Backups', 'We perform reasonable backup procedures for supported cloud-based Services, intended primarily for disaster recovery; backups are not guaranteed to restore every version of your data, and you remain responsible for maintaining independent backups of critical business information. Backup retention periods may change over time based on operational requirements.'],
      ['Third-Party Services', 'Our Services rely on third-party providers for infrastructure and operational functions, including cloud infrastructure, data storage, email delivery, security, content delivery, payment processing, authentication, analytics, and monitoring. Use of such third-party services is subject to their own terms and privacy practices, and we are not responsible for outages, delays, or failures caused solely by third-party providers beyond our reasonable control.'],
      ['Disclaimer of Warranties', 'To the fullest extent permitted by law, the Services are provided "as is" and "as available." We do not guarantee that the Services will operate without interruption, be free from errors or defects, meet every business requirement, be compatible with every device or third-party service, or prevent all data loss or security incidents. Nothing in these Terms limits any warranty that cannot legally be excluded.'],
      ['Limitation of Liability', 'To the fullest extent permitted by law, Saw Yun LLC and its owner, officers, employees, contractors, and affiliates are not liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from use of, or inability to use, the Services — including loss of profits, revenue, business opportunities, customers, business interruption, data loss, or goodwill. Where liability cannot legally be excluded, our total liability for any claim shall not exceed the amount you paid for the affected Service in the twelve (12) months preceding the claim. Nothing here excludes liability for fraud, intentional misconduct, or any liability that cannot legally be limited.'],
      ['Indemnification', 'You agree to indemnify, defend, and hold harmless Saw Yun LLC and its owner, employees, contractors, and representatives from claims, damages, liabilities, losses, costs, or expenses (including reasonable legal fees) arising from your violation of these Terms, unlawful use of the Services, infringement of another’s rights, content or data you upload or store, or violation of applicable law.'],
      ['Export Compliance', 'You agree not to use, export, re-export, or transfer our Software or Services in violation of applicable United States export control laws, sanctions, or trade regulations, and you are responsible for ensuring your use complies with the laws of your own jurisdiction.'],
      ['Force Majeure', 'We are not responsible for delays or failures caused by events beyond our reasonable control, including natural disasters, fire, flood, war, terrorism, civil unrest, government actions, internet or utility failures, cybersecurity incidents, labor disputes, pandemic-related disruptions, or failures of third-party infrastructure providers. Performance of affected obligations may be suspended for the duration of such an event.'],
      ['Governing Law', 'These Terms are governed by and construed in accordance with the laws of the State of Montana, United States, without regard to conflict-of-law principles. Where applicable law requires otherwise, mandatory consumer protection laws of your country or jurisdiction may continue to apply.'],
      ['Dispute Resolution', 'Before initiating legal proceedings, we encourage you to contact us so we may attempt to resolve disputes informally through good-faith communication. If a dispute cannot be resolved informally, it will be resolved in accordance with applicable law and the governing law specified above; nothing here prevents either party from seeking emergency injunctive or equitable relief where legally appropriate.'],
      ['Changes to These Terms', 'We may update these Terms from time to time to reflect changes in our Services, applicable laws, security practices, business operations, or new products. Updated Terms become effective on the published Effective Date, and continued use of the Services after that constitutes acceptance; where legally required, we will provide advance notice of material changes.'],
      ['Severability', 'If any provision of these Terms is found unlawful, invalid, or unenforceable, the remaining provisions remain in full force and effect, and the invalid provision will be interpreted or modified only to the minimum extent necessary to make it enforceable while preserving its original intent.'],
      ['Entire Agreement', 'These Terms, together with our Privacy Policy, Refund Policy, End User License Agreement (where applicable), Reseller & Referral Partner Agreement (where applicable), and any product-specific terms incorporated by reference, constitute the entire agreement between you and Saw Yun LLC and supersede any prior agreements or communications on the same subject matter.'],
      ['Contact', 'Questions about these Terms can be sent to legal@sawyuntech.com. General support: support@sawyuntech.com. Billing & administration: admin@sawyuntech.com.'],
    ],
  },
  privacy: {
    num: '02',
    label: 'Privacy Policy',
    title: 'Privacy Policy',
    version: 'v1',
    applies: 'Applies to every visitor, customer, and business using any Saw Yun LLC product or service.',
    intro: 'Saw Yun LLC ("Saw Yun," "we," "us," "our") respects your privacy. This Privacy Policy explains what information we collect, how we use it, and the choices you have, across all of our current and future products and services (collectively, the "Services"). By using the Services, you agree to the collection and use of information as described in this Policy.',
    sections: [
      ['Information We Collect', 'Information required to provide the Services includes your name, email address, business name, device ID, IP address, browser information, operating system, crash logs, product usage analytics, license keys, payment references, and any customer database records you enter into the Services. Depending on how you use the Services, we may also collect optional information such as phone number, business address, employee information, uploaded files, and inventory data.'],
      ['How We Use Information', 'We use the information we collect to create and manage your account and license; provide, operate, and maintain the Services; process payments and verify transactions; activate and validate software licenses; send administrative communications such as receipts, password resets, and service notices; provide customer support; monitor, diagnose, and improve the Services; detect and prevent fraud, abuse, and security issues; and comply with legal obligations.'],
      ['How We Share Information', 'We do not sell your personal information. We share it only with service providers who help us operate the Services — currently Cloudflare (including Cloudflare Tunnel and Cloudflare R2), Mailtrap for transactional email, and our self-hosted VPS provider — and, as we grow, may add providers such as payment processors, analytics providers, and AI providers, with this Policy updated accordingly. We may also share information where required by law or legal process, to protect the rights, property, or safety of Saw Yun LLC or others, or as part of a merger, acquisition, or sale of assets.'],
      ['Data Retention', 'We retain account information until your deletion request plus 90 days; backups for 90 days; crash logs for 12 months; billing records for 7 years; and license records while your license is active plus a reasonable period afterward, unless a longer period is required by law.'],
      ['Account Deletion', 'You may request deletion of your account and associated data by contacting support@sawyuntech.com or legal@sawyuntech.com. We may retain certain information after a deletion request where necessary for legal obligations, accounting and tax requirements, fraud prevention, security, or license verification; backups containing your data expire naturally rather than being individually purged.'],
      ['Data Security', 'We use technical and organizational measures designed to protect your information, including JWT-based authentication, Cloudflare infrastructure, and self-hosted servers running PostgreSQL and Redis. No system is completely secure, and we cannot guarantee absolute security.'],
      ['International Data Transfers', 'Saw Yun LLC serves customers worldwide. Because our infrastructure and service providers may operate in the United States and other countries, your information may be transferred to and processed in countries other than your own. As our international customer base grows, we are working toward aligning our practices with frameworks such as the GDPR and CCPA/CPRA where applicable.'],
      ['Your Rights', 'Depending on your location, you may have rights to access, correct, delete, or export your personal information, or to object to or restrict certain processing. To exercise these rights, contact legal@sawyuntech.com; we will respond in accordance with applicable law.'],
      ['Children’s Privacy', 'The Services are not directed to individuals under 18 years old, and we do not knowingly collect personal information from children. If you believe a minor has provided us with personal information, contact legal@sawyuntech.com and we will take appropriate action.'],
      ['Cookies & Similar Technologies', 'Our websites and applications may use cookies or similar technologies necessary for authentication, session management, and basic analytics. We do not currently use cookies for third-party advertising.'],
      ['Changes to This Policy', 'We may update this Privacy Policy from time to time. Material changes will be communicated via email or notice within the Services, and continued use after changes take effect constitutes acceptance of the updated Policy.'],
      ['Contact', 'General support: support@sawyuntech.com. Legal and privacy inquiries: legal@sawyuntech.com. Billing & administration: admin@sawyuntech.com. Saw Yun LLC is a Montana single-member LLC; our business address is not publicly published, so please reach us by email for all inquiries.'],
    ],
  },
  refund: {
    num: '03',
    label: 'Refund Policy',
    title: 'Refund Policy',
    version: 'v1',
    applies: 'Applies to every product and service offered by Saw Yun LLC. Also referenced at checkout.',
    intro: 'This Refund Policy applies to all products and services offered by Saw Yun LLC, current and future, unless a specific product states otherwise at the time of purchase.',
    sections: [
      ['Desktop Software Products (Lifetime License)', 'Where a desktop software product is licensed under a one-time, lifetime license model, the purchase is generally non-refundable once the license has been successfully activated. We will consider a refund in specific cases: duplicate payment, failed activation caused by a fault on our end that could not be resolved, where required by law, or case-by-case administrative approval.'],
      ['Subscription Products', 'Products billed on a recurring subscription basis — whether a SaaS product or a subscription-licensed desktop product — do not receive prorated or partial refunds for unused periods if you cancel or downgrade mid-cycle. Canceling a subscription stops future renewals but does not retroactively refund amounts already paid; you retain access through the end of the period you’ve already paid for.'],
      ['Free Trials', 'Free trial programs — currently a 30-day trial and a 45-day referral trial — do not require payment during the trial, so no refund applies to trial usage. If you do not cancel before a trial converts to a paid subscription, standard subscription billing and refund rules apply from that point forward.'],
      ['How to Request a Refund', 'Email admin@sawyuntech.com with your account or business name, the product and plan purchased, your payment reference or transaction ID, and the reason for your request. We review refund requests on a case-by-case basis and may request additional information or manual verification before approving a refund.'],
      ['Disputes & Chargebacks', 'Before filing a payment dispute or chargeback with your bank or payment provider, please contact admin@sawyuntech.com so we can attempt to resolve the issue directly. Filing an unauthorized or fraudulent chargeback may result in suspension or termination of your account and access to the Services.'],
      ['Changes to This Policy', 'We may update this Refund Policy from time to time. The policy in effect at the time of your purchase governs that transaction, unless we are required by law to apply an updated policy retroactively.'],
      ['Contact', 'Billing & refund requests: admin@sawyuntech.com. General support: support@sawyuntech.com.'],
    ],
  },
  eula: {
    num: '04',
    label: 'End User License Agreement',
    title: 'End User License Agreement',
    version: 'v1',
    applies: 'Presented for acceptance before downloading or activating any Saw Yun LLC desktop software product.',
    intro: 'This End User License Agreement ("EULA") is a legal agreement between you and Saw Yun LLC, a single-member limited liability company registered in the State of Montana, United States, governing your use of any desktop software product we license to you, now or in the future (each, the "Software"). This EULA is incorporated by reference into our Terms of Service.',
    sections: [
      ['License Grant', 'Subject to your compliance with this EULA and payment of applicable fees, Saw Yun grants you a limited, non-exclusive, non-transferable (except as described below), revocable license to install and use the Software for your internal business purposes, in accordance with your purchased plan and activation limits. The Software is licensed, not sold — Saw Yun and its licensors retain all right, title, and interest in it, and no ownership rights are transferred to you.'],
      ['Lifetime License', 'Where the Software is sold under a "lifetime license" model, your license does not expire and does not require recurring subscription payments, and it includes free access to all future updates and major versions of the same Software product — including new features we add over time, such as future cloud synchronization — for as long as that product is offered and supported by Saw Yun LLC. A lifetime license does not extend to a substantially different or separately branded product released as a new offering. If a future feature relies on ongoing third-party or infrastructure costs to operate, we may offer that specific feature under separate optional terms, disclosed clearly before you opt in.'],
      ['Activation', 'The Software requires activation to unlock full functionality, tied to a specific device and license key. The number of devices you may activate depends on your purchased plan. Once activated, the Software may generally be used offline; certain features may require periodic online verification or may only be available online. We may offer cloud synchronization or other online-dependent features in the future, subject to additional terms at that time.'],
      ['License Transfer & Device Changes', 'License sharing and resale are prohibited. License transfer to a new owner is permitted only in accordance with our activation policy in effect at the time of transfer — contact admin@sawyuntech.com to request one. Moving your license to a new or replacement device may require administrative approval and is subject to reasonable limits to prevent abuse.'],
      ['Restrictions', 'You agree not to copy, modify, or create derivative works of the Software except as expressly permitted; reverse engineer, decompile, or disassemble it except where prohibited by law; remove or obscure proprietary notices; rent, lease, sell, sublicense, or otherwise transfer the Software except as permitted above; use it to build a competing product; or circumvent any license activation or verification mechanism.'],
      ['Updates & Support', 'We may, but are not obligated to, provide updates, bug fixes, or support for the Software, which may be subject to additional terms in the future. We do not currently commit to a specific support-response service level; support requests can be sent to support@sawyuntech.com.'],
      ['Ownership', 'The Software, including all source code, object code, structure, and organization, remains the exclusive property of Saw Yun LLC and its licensors. This EULA does not grant you any rights to our trademarks, service marks, or logos.'],
      ['Termination', 'This EULA and your license remain effective until terminated. We may terminate your license immediately if you breach this EULA, including through unauthorized sharing, resale, or circumvention of activation controls. Upon termination, you must stop using the Software and, if requested, confirm deactivation or removal from your devices. Provisions that by their nature should survive termination will continue to apply.'],
      ['Disclaimer of Warranty', 'The Software is provided "as is" without warranty of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Software will be error-free or uninterrupted.'],
      ['Limitation of Liability', 'To the maximum extent permitted by law, Saw Yun LLC is not liable for indirect, incidental, special, consequential, or punitive damages arising from your use of the Software. Our total liability under this EULA will not exceed the amount you paid for the applicable license.'],
      ['Governing Law', 'This EULA is governed by the laws of the State of Montana, United States, without regard to conflict-of-law principles, consistent with our Terms of Service.'],
      ['Entire Agreement', 'This EULA, together with our Terms of Service and Privacy Policy, constitutes the entire agreement between you and Saw Yun LLC regarding the Software and supersedes any prior agreements relating to it.'],
      ['Contact', 'General support: support@sawyuntech.com. Legal inquiries: legal@sawyuntech.com. License transfers & administration: admin@sawyuntech.com.'],
    ],
  },
  reseller: {
    num: '06',
    label: 'Reseller & Referral Partner Agreement',
    title: 'Reseller & Referral Partner Agreement',
    version: 'v1',
    applies: 'Presented for acceptance during reseller/referral partner program enrollment — not part of the standard customer flow.',
    intro: 'This Reseller & Referral Partner Agreement governs your participation as a reseller or referral partner in the reseller/referral program (the "Program") offered as part of an eligible SaaS product, operated by Saw Yun LLC. It supplements, and is incorporated into, our Terms of Service, and controls over the Terms on reseller-specific matters. By enrolling in the Program, generating or sharing a referral link or code, or receiving any commission or payout, you agree to this Agreement.',
    sections: [
      ['Eligibility', 'You must be at least 18 years old and hold a valid Saw Yun account to participate. We may approve, decline, suspend, or remove any reseller from the Program at our discretion.'],
      ['How the Program Works', 'We provide you with a unique referral link and/or code to share with prospective customers. Referred customers who sign up using your link or code may be eligible for a referral trial (currently 45 days, subject to change). When a referred customer converts to a paid subscription, you may earn a commission as described below; referral attribution, trial terms, and eligible products may change with reasonable notice of material changes.'],
      ['Commissions', 'The commission rate is currently 10% of the referred customer’s payment. Commissions are earned once when a referred customer first activates a paid subscription, and again if that customer later upgrades to a higher-tier plan, calculated on the upgrade payment — commissions are not currently earned again on ordinary renewals at the same plan, though we may introduce renewal-based or other recurring commission structures in the future. Commissions apply only to genuine, active paying subscriptions resulting directly from your referral, not to your own account or fraudulent or duplicate signups, and rates or structures may be updated for new referrals going forward.'],
      ['Wallet & Payouts', 'Earned commissions accrue to a reseller wallet balance denominated in Myanmar Kyats (MMK). The minimum payout threshold is 50,000 MMK; balances below this amount roll over until the threshold is met. Payouts are processed on request once your balance meets or exceeds the threshold, following our standard payment methods, which may include bank transfer, mobile payments, digital wallets, or other approved methods, and manual verification may be required before release. You are responsible for providing accurate payout information.'],
      ['Clawbacks & Reversals', 'We may reverse, deduct, or claw back a commission from your wallet balance — including from future earnings if the balance is insufficient — if the referred customer receives a refund, cancels within an initial period, or has their subscription terminated for breach of the Terms of Service; the referral is later found to be fraudulent, self-referred, or otherwise ineligible; or the commission was credited in error.'],
      ['Marketing & Use of Brand', 'We grant you a limited, non-exclusive, revocable license to use Saw Yun’s name, logo, and referral materials solely to promote the applicable Product through the Program, in accordance with any brand guidelines provided. You may not make false or misleading claims about the Product or Saw Yun LLC, use paid search advertising on our brand terms without permission, spam or use deceptive practices, or imply you are an employee or official representative of Saw Yun LLC. This license ends automatically if you leave the Program.'],
      ['Prohibited Conduct', 'You agree not to create fake, duplicate, or self-referred accounts to generate commissions; circumvent referral attribution or tracking; or otherwise violate our Terms of Service or Acceptable Use rules. Violations may result in immediate suspension or termination from the Program, forfeiture of unpaid commissions, and/or clawback of prior payouts.'],
      ['Relationship of the Parties', 'You participate as an independent contractor, not as an employee, partner, joint venturer, or agent of Saw Yun LLC, with no authority to bind us to any obligation. You are solely responsible for any taxes owed on commissions or payouts you receive.'],
      ['Term & Termination', 'Either party may terminate participation at any time, for any reason, with or without notice. Commissions earned from legitimate, non-reversed referrals prior to termination remain payable subject to our payout schedule and threshold, unless termination was for cause, in which case unpaid commissions may be forfeited; your license to use our brand and marketing materials ends immediately upon termination.'],
      ['Disclaimer & Limitation of Liability', 'The Program is provided "as is," with no guaranteed minimum level of referrals, conversions, or earnings. To the maximum extent permitted by law, our total liability to you under this Agreement will not exceed the total commissions paid to you in the three (3) months preceding the claim.'],
      ['Governing Law', 'This Agreement is governed by the laws of the State of Montana, United States, without regard to conflict-of-law principles, consistent with our Terms of Service.'],
      ['Changes to This Agreement', 'We may update this Agreement from time to time. Material changes will be communicated via email or notice within the Services, and continued participation after changes take effect constitutes acceptance of the updated Agreement.'],
      ['Contact', 'Reseller program support: admin@sawyuntech.com. General support: support@sawyuntech.com. Legal inquiries: legal@sawyuntech.com.'],
    ],
  },
};

// Numbering intentionally skips 05 — that slot is the internal Company Legal Profile, which is never published to the site.
const TAB_ORDER = ['terms', 'privacy', 'refund', 'eula', 'reseller'];

export default function Legal() {
  const { doc: docParam } = useParams();
  const navigate = useNavigate();
  const doc = LEGAL_DOCS[docParam] ? docParam : 'terms';
  const active = LEGAL_DOCS[doc];

  return (
    <div data-screen-label="Legal" className="fade-up">
      <div className="page-header">
        <div style={{ fontSize: 12.5, fontWeight: 700, letterSpacing: 1.5, color: BLUE, marginBottom: 12 }}>LEGAL</div>
        <h1 className="page-title" style={{ fontFamily: FONT_HEAD, fontWeight: 700, letterSpacing: -1, margin: '0 0 16px', color: NAVY }}>
          Policies &amp; agreements
        </h1>
        <p style={{ fontSize: 16.5, lineHeight: 1.65, color: MUTED, maxWidth: 640, margin: 0 }}>
          The documents that govern using our products and working with Saw Yun LLC.
        </p>
      </div>

      <div className="legal-layout">
        <div className="legal-sidebar-wrap">
          <div className="legal-sidebar">
            {TAB_ORDER.map((id) => {
              const t = LEGAL_DOCS[id];
              const isActive = id === doc;
              return (
                <div
                  key={id}
                  onClick={() => navigate(`/legal/${id}`)}
                  style={{
                    display: 'flex', alignItems: 'baseline', gap: 10, padding: '13px 16px', borderRadius: 10,
                    background: isActive ? 'rgba(61,107,255,0.08)' : 'transparent', cursor: 'pointer',
                    border: isActive ? '1px solid rgba(61,107,255,0.18)' : '1px solid transparent',
                  }}
                >
                  <span style={{ fontSize: 12, fontWeight: 700, color: isActive ? BLUE : 'rgba(11,18,32,0.32)', fontFamily: FONT_HEAD }}>{t.num}</span>
                  <span style={{ fontSize: 14.5, fontWeight: 700, color: isActive ? NAVY : MUTED }}>{t.label}</span>
                </div>
              );
            })}
          </div>
        </div>

        <div className="legal-content">
          <div style={{
            fontSize: 12, fontWeight: 700, letterSpacing: 0.5, color: MUTED,
            background: 'rgba(11,18,32,0.04)', borderRadius: 8, padding: '10px 14px', marginBottom: 8,
          }}>
            Effective July 20, 2026 · Governed by the laws of the State of Montana, USA.
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 10, margin: '20px 0 4px', flexWrap: 'wrap' }}>
            <h2 style={{ fontFamily: FONT_HEAD, fontWeight: 700, fontSize: 24, color: NAVY, margin: 0 }}>{active.title}</h2>
            <span style={{
              fontSize: 11.5, fontWeight: 700, color: BLUE, background: 'rgba(61,107,255,0.08)',
              padding: '3px 10px', borderRadius: 100, whiteSpace: 'nowrap',
            }}>{active.version}</span>
          </div>
          <div style={{ fontSize: 13, color: MUTED, marginBottom: 6 }}>{active.applies}</div>
          <p style={{ fontSize: 14.5, lineHeight: 1.75, color: MUTED, margin: '0 0 4px' }}>{active.intro}</p>
          {active.sections.map(([heading, body]) => (
            <div key={heading}>
              <div style={{ fontFamily: FONT_HEAD, fontWeight: 700, fontSize: 16, color: NAVY, margin: '26px 0 8px' }}>{heading}</div>
              <p style={{ fontSize: 14.5, lineHeight: 1.75, color: MUTED, margin: '0 0 4px' }}>{body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
